# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Run Tests on Post Deploy

on: 
  workflow_run:
    workflows: ["Manual Run"]
    types:
      - completed

jobs:
  e2e-tests:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: yarn

      if: ${{ github.event.workflow_run.conclusion == 'success' }}

    - run: yarn run test
    - run: yarn run test:mutation
    - run: yarn playwright install
    - run: yarn run e2e

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}  
      with:
        name: relatorio
        path: ./playwright-report
