name: 'Full Execution'

on:
  workflow_dispatch:

jobs:
  inspecao:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependências
        run: yarn

      - name: Checando padronizacao do codigo
        run: yarn lint

  unidade:
    needs: inspecao
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependências
        run: yarn

      - name: Checando padronizacao do codigo
        run: yarn test

  mutatuion-tests:
    needs: unidade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependências
        run: yarn

      - name: Rodando testes de mutação
        run: yarn run test:mutation
  e2e-tests:
    needs: unidade
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando Dependências
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Rodar testes e2e
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio
          path: ./playwright-report

      - uses: dorny/test-reporter@v1.9.1
        with:
          name: Test Report
          path: ./playwright-report
          reporter: 'jest-junit'

  deploy:
    needs: [e2e-tests, mutatuion-tests]
    runs-on: ubuntu-latest
    steps:
      - name: Simulacao deploy
        run: echo "Simulando deploy"
